### ISSUE TITLE
Im confused

### ISSUE THREAD

**Issue by MakiRollDev** [ioncodes/SteamManifestFixer#1]
Ik  you prob only did this as a small side project but im deeply confused how to use the tool

the readme says that i should run the exe . . . wich doesnt exist

**Comment by ioncodes** [comment]
You have to compile it first. In case you don't have Visual Studio installed, I compiled it for you. You can find it attached to this comment :)
[SteamManifestFixer.zip](https://github.com/ioncodes/SteamManifestFixer/files/5110530/SteamManifestFixer.zip)
